//*****************************************************************************
//  FILE NAME: DATATYPE.H
//*****************************************************************************

#ifndef DATATYPE_H
#define DATATYPE_H

typedef char                CHAR;
typedef unsigned char       UCHAR;
typedef int                 INT;
typedef unsigned int        UINT;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef signed int          SINT;

typedef unsigned char       BYTE;
typedef unsigned short      UWORD;
typedef unsigned short      DWORD;
typedef unsigned long int   ULNG;
typedef unsigned char       CMDBITVAR;
typedef unsigned char       GENBITVAR;
typedef unsigned char       DMDBITVAR;
typedef unsigned char       V42BITVAR;
typedef unsigned char       V42BISBITVAR;
typedef unsigned char       FAXCDBITVAR;
typedef unsigned char       FAXDBITVAR;
typedef unsigned char       VOICECDBITVAR;
typedef unsigned char       VOICEDBITVAR;

#endif

//*****************************************************************************
//  END OF FILE
//*****************************************************************************
