
;------------------------------------------------------------------------------
; FILE NAME : TABLES.H
;------------------------------------------------------------------------------

;Filter coefficients for column tones
.global    LOWCos                      

;Initial input to the Digital oscillator for row tones = -Asin(2pi*Ftone/Fsamp)
.global    LOWImp

;Filter coefficients for column tones                 
.global    HIGHCos

;Initial input to Digital Oscillator for column tones  -A*sin(2pi*Ftone/Fsamp)
.global    HIGHImp

;------------------------------------------------------------------------------
; END OF FILE
;------------------------------------------------------------------------------

